name: Commit changes to file

on:
  push:
    branches:
      - main

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Make changes to file
        run: echo "New content" >> file.txt
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add file.txt
          git commit -m "Auto-commit: Add new content to file"
          git push
